apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: pytorch-simple
  labels:
    trainer.kubeflow.org/framework: pytorch
spec:
  mlPolicy:
    numNodes: 1  # 기본 단일 노드
    torch:
      numProcPerNode: "auto"  # GPU 있으면 GPU 수, 없으면 CPU 수 자동 감지
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime
                      env:
                        - name: PYTHONUNBUFFERED
                          value: "1"
