apiVersion: v1
kind: ConfigMap
metadata:
  name: pytorch-pet-setup
  namespace: kubeflow-system
data:
  setup_pytorch_env.sh: |
    #!/bin/bash
    # PyTorch λ¶„μ‚° ν•™μµμ© ν™κ²½λ³€μ μ„¤μ • μ¤ν¬λ¦½νΈ
    # Kubeflow Training Operator v2μ PET ν™κ²½λ³€μλ¥Ό PyTorch ν‘μ¤€μΌλ΅ λ³€ν™

    set -e

    echo "==========================================="
    echo "π”§ PyTorch λ¶„μ‚° ν•™μµ ν™κ²½ μ„¤μ • μ‹μ‘"
    echo "==========================================="

    # PET ν™κ²½λ³€μ ν™•μΈ
    if [ -z "$PET_NODE_RANK" ]; then
        echo "β PET ν™κ²½λ³€μκ°€ μ—†μµλ‹λ‹¤"
        exit 1
    fi

    # PyTorch ν‘μ¤€ ν™κ²½λ³€μλ΅ λ³€ν™
    export RANK=$PET_NODE_RANK
    export WORLD_SIZE=$PET_NNODES
    export MASTER_ADDR=$PET_MASTER_ADDR
    export MASTER_PORT=$PET_MASTER_PORT
    export LOCAL_RANK=0  # numProcPerNode=1μ΄λ―€λ΅ ν•­μƒ 0

    # PyTorch λ¶„μ‚° ν•™μµ λ°±μ—”λ“ μ„¤μ •
    export NCCL_DEBUG=INFO  # λ””λ²„κΉ…μ© (ν•„μ”μ‹ μ κ±°)

    echo ""
    echo "β… PyTorch ν™κ²½λ³€μ μ„¤μ • μ™„λ£!"
    echo "  - RANK: $RANK"
    echo "  - WORLD_SIZE: $WORLD_SIZE"
    echo "  - MASTER_ADDR: $MASTER_ADDR"
    echo "  - MASTER_PORT: $MASTER_PORT"
    echo "  - LOCAL_RANK: $LOCAL_RANK"
    echo "==========================================="
    echo ""
