apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: pytorch-runtime
  labels:
    trainer.kubeflow.org/framework: pytorch
spec:
  mlPolicy:
    numNodes: 1  # 기본 단일 노드
    torch:
      numProcPerNode: "auto"  # GPU 있으면 GPU 수, 없으면 CPU 수 자동 감지
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  volumes:
                    - name: git-clone-volume
                      emptyDir: {}
                  initContainers:
                    - name: git-clone
                      image: alpine/git:v2.36.2
                      imagePullPolicy: IfNotPresent
                      command:
                        - sh
                        - -c
                        - |
                          set -e
                          # Downward API annotation overrides (if present)
                          if [ -n "$GIT_SYNC_REPO_ANNOT" ]; then GIT_SYNC_REPO="$GIT_SYNC_REPO_ANNOT"; fi
                          if [ -n "$GIT_SYNC_BRANCH_ANNOT" ]; then GIT_SYNC_BRANCH="$GIT_SYNC_BRANCH_ANNOT"; fi
                          if [ -n "$GIT_SYNC_ROOT_ANNOT" ]; then GIT_SYNC_ROOT="$GIT_SYNC_ROOT_ANNOT"; fi
                          if [ -n "$COMMAND_ANNOT" ]; then COMMAND="$COMMAND_ANNOT"; fi

                          echo "[git-clone] repo=$GIT_SYNC_REPO branch=$GIT_SYNC_BRANCH root=$GIT_SYNC_ROOT"
                          git clone "$GIT_SYNC_REPO" --branch "$GIT_SYNC_BRANCH" "$GIT_SYNC_ROOT";
                          chmod -R 777 "$GIT_SYNC_ROOT";
                      env:
                        - name: GIT_SYNC_REPO
                          value: https://github.com/xiilab/astrago-trainer.git
                        - name: GIT_SYNC_BRANCH
                          value: main
                        - name: GIT_SYNC_MOUNT_PATH
                          value: "/horovod"
                        - name: REPOSITORY_TYPE
                          value: USER
                        - name: COMMAND
                          value: "python examples/pytorch/pytorch_mnist.py"
                        - name: GIT_SYNC_TIMEOUT
                          value: "600"
                        - name: GIT_SYNC_ROOT
                          value: /git/code
                        - name: GIT_SYNC_DEST
                          value: code
                        - name: GIT_SYNC_PERMISSIONS
                          value: "true"
                        - name: GIT_SYNC_ONE_TIME
                          value: "true"
                        - name: SOURCE_CODE_ID
                          value: "1"
                        # Annotation-driven overrides
                        - name: GIT_SYNC_REPO_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-repo']
                        - name: GIT_SYNC_BRANCH_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-branch']
                        - name: GIT_SYNC_ROOT_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-root']
                        - name: COMMAND_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-command']
                      resources:
                        limits:
                          cpu: 500m
                          memory: 500Mi
                        requests:
                          cpu: 500m
                          memory: 500Mi
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                      volumeMounts:
                        - mountPath: /git
                          name: git-clone-volume
                  containers:
                    - name: node
                      image: pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime
                      volumeMounts:
                        - name: git-clone-volume
                          mountPath: /git
                        # train-script는 TrainJob에서 필요시 추가 (현재는 git-clone 사용)
                      env:
                        - name: PYTHONUNBUFFERED
                          value: "1"


