apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: tensorflow-distributed
  labels:
    trainer.kubeflow.org/framework: tensorflow
spec:
  mlPolicy:
    numNodes: 1  # ê¸°ë³¸ ë‹¨ì¼ ë…¸ë“œ
    # TensorFlow MultiWorkerMirroredStrategyëŠ” ìžì²´ í†µì‹  ì‚¬ìš© (MPI ë¶ˆí•„ìš”)
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  volumes:
                    - name: shared-env
                      emptyDir: {}

                  initContainers:
                    - name: tf-config-generator
                      image: busybox:latest
                      command:
                        - sh
                        - -c
                        - |
                          #!/bin/sh
                          set -e

                          echo "=========================================="
                          echo "ðŸ”§ TF_CONFIG ìƒì„± ì‹œìž‘"
                          echo "=========================================="

                          # Hostnameì—ì„œ ì •ë³´ ì¶”ì¶œ
                          HOSTNAME=$(hostname)
                          echo "Hostname: $HOSTNAME"

                          JOB_NAME=$(echo $HOSTNAME | sed 's/-node-0-.*//')
                          WORKER_INDEX=$(echo $HOSTNAME | grep -o '[0-9]*$')
                          NUM_WORKERS=${PET_NNODES:-1}
                          NAMESPACE=${NAMESPACE:-default}
                          PORT=${TF_PORT:-2222}

                          echo "Job Name: $JOB_NAME"
                          echo "Worker Index: $WORKER_INDEX"
                          echo "Total Workers: $NUM_WORKERS"
                          echo "Namespace: $NAMESPACE"
                          echo "Port: $PORT"

                          # Worker ëª©ë¡ ìƒì„±
                          WORKERS="["
                          for i in $(seq 0 $((NUM_WORKERS-1))); do
                              if [ $i -gt 0 ]; then
                                  WORKERS="$WORKERS,"
                              fi
                              WORKER_ADDR="${JOB_NAME}-node-0-${i}.${JOB_NAME}.${NAMESPACE}.svc.cluster.local:${PORT}"
                              WORKERS="$WORKERS\\\"${WORKER_ADDR}\\\""
                          done
                          WORKERS="$WORKERS]"

                          # TF_CONFIG íŒŒì¼ì— ì €ìž¥
                          cat > /shared-env/tf_config.env << EOF
                          export TF_CONFIG="{\"cluster\":{\"worker\":$WORKERS},\"task\":{\"type\":\"worker\",\"index\":$WORKER_INDEX}}"
                          EOF

                          echo ""
                          echo "âœ… TF_CONFIG ìƒì„± ì™„ë£Œ!"
                          cat /shared-env/tf_config.env
                          echo "=========================================="
                      env:
                        - name: NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                        - name: PET_NNODES
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.labels['trainer.kubeflow.org/num-nodes']
                      volumeMounts:
                        - name: shared-env
                          mountPath: /shared-env

                  containers:
                    - name: node
                      image: tensorflow/tensorflow:2.15.0-gpu
                      env:
                        - name: PYTHONUNBUFFERED
                          value: "1"
                        - name: NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                      volumeMounts:
                        - name: shared-env
                          mountPath: /shared-env
