apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: tensorflow-runtime
  labels:
    trainer.kubeflow.org/framework: tensorflow
spec:
  mlPolicy:
    numNodes: 1  # ê¸°ë³¸ ë‹¨ì¼ ë…¸ë“œ
    # TensorFlow MultiWorkerMirroredStrategyëŠ” ìžì²´ í†µì‹  ì‚¬ìš© (MPI ë¶ˆí•„ìš”)
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  volumes:
                    - name: shared-env
                      emptyDir: {}
                    - name: git-clone-volume
                      emptyDir: {}

                  initContainers:
                    - name: tf-config-generator
                      image: busybox:latest
                      command:
                        - sh
                        - -c
                        - |
                          #!/bin/sh
                          set -e

                          echo "=========================================="
                          echo "ðŸ”§ TF_CONFIG ìƒì„± ì‹œìž‘"
                          echo "=========================================="

                          # Hostnameì—ì„œ ì •ë³´ ì¶”ì¶œ
                          HOSTNAME=$(hostname)
                          echo "Hostname: $HOSTNAME"

                          JOB_NAME=$(echo $HOSTNAME | sed 's/-node-0-.*//')
                          WORKER_INDEX=$(echo $HOSTNAME | grep -o '[0-9]*$')
                          NUM_WORKERS=${PET_NNODES:-1}
                          NAMESPACE=${NAMESPACE:-default}
                          PORT=${TF_PORT:-2222}

                          echo "Job Name: $JOB_NAME"
                          echo "Worker Index: $WORKER_INDEX"
                          echo "Total Workers: $NUM_WORKERS"
                          echo "Namespace: $NAMESPACE"
                          echo "Port: $PORT"

                          # Worker ëª©ë¡ ìƒì„±
                          WORKERS="["
                          for i in $(seq 0 $((NUM_WORKERS-1))); do
                              if [ $i -gt 0 ]; then
                                  WORKERS="$WORKERS,"
                              fi
                              WORKER_ADDR="${JOB_NAME}-node-0-${i}.${JOB_NAME}.${NAMESPACE}.svc.cluster.local:${PORT}"
                              WORKERS="$WORKERS\\\"${WORKER_ADDR}\\\""
                          done
                          WORKERS="$WORKERS]"

                          # TF_CONFIG íŒŒì¼ì— ì €ìž¥
                          cat > /shared-env/tf_config.env << EOF
                          export TF_CONFIG="{\"cluster\":{\"worker\":$WORKERS},\"task\":{\"type\":\"worker\",\"index\":$WORKER_INDEX}}"
                          EOF

                          echo ""
                          echo "âœ… TF_CONFIG ìƒì„± ì™„ë£Œ!"
                          cat /shared-env/tf_config.env
                          echo "=========================================="
                      env:
                        - name: NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                        - name: PET_NNODES
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.labels['trainer.kubeflow.org/num-nodes']
                      volumeMounts:
                        - name: shared-env
                          mountPath: /shared-env
                    - name: git-clone
                      image: alpine/git:v2.36.2
                      imagePullPolicy: IfNotPresent
                      command:
                        - sh
                        - -c
                        - |
                          set -e
                          # Downward API annotation overrides (if present)
                          if [ -n "$GIT_SYNC_REPO_ANNOT" ]; then GIT_SYNC_REPO="$GIT_SYNC_REPO_ANNOT"; fi
                          if [ -n "$GIT_SYNC_BRANCH_ANNOT" ]; then GIT_SYNC_BRANCH="$GIT_SYNC_BRANCH_ANNOT"; fi
                          if [ -n "$GIT_SYNC_ROOT_ANNOT" ]; then GIT_SYNC_ROOT="$GIT_SYNC_ROOT_ANNOT"; fi
                          if [ -n "$COMMAND_ANNOT" ]; then COMMAND="$COMMAND_ANNOT"; fi

                          echo "[git-clone] repo=$GIT_SYNC_REPO branch=$GIT_SYNC_BRANCH root=$GIT_SYNC_ROOT"
                          git clone "$GIT_SYNC_REPO" --branch "$GIT_SYNC_BRANCH" "$GIT_SYNC_ROOT";
                          chmod -R 777 "$GIT_SYNC_ROOT";
                      env:
                        - name: GIT_SYNC_REPO
                          value: https://github.com/xiilab/astrago-trainer.git
                        - name: GIT_SYNC_BRANCH
                          value: main
                        - name: GIT_SYNC_MOUNT_PATH
                          value: "/horovod"
                        - name: REPOSITORY_TYPE
                          value: USER
                        - name: COMMAND
                          value: "python examples/pytorch/pytorch_mnist.py"
                        - name: GIT_SYNC_TIMEOUT
                          value: "600"
                        - name: GIT_SYNC_ROOT
                          value: /git/code
                        - name: GIT_SYNC_DEST
                          value: code
                        - name: GIT_SYNC_PERMISSIONS
                          value: "true"
                        - name: GIT_SYNC_ONE_TIME
                          value: "true"
                        - name: SOURCE_CODE_ID
                          value: "1"
                        # Annotation-driven overrides
                        - name: GIT_SYNC_REPO_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-repo']
                        - name: GIT_SYNC_BRANCH_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-branch']
                        - name: GIT_SYNC_ROOT_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-root']
                        - name: COMMAND_ANNOT
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.annotations['trainer.kubeflow.org/git-sync-command']
                      resources:
                        limits:
                          cpu: 500m
                          memory: 500Mi
                        requests:
                          cpu: 500m
                          memory: 500Mi
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                      volumeMounts:
                        - mountPath: /git
                          name: git-clone-volume

                  containers:
                    - name: node
                      image: tensorflow/tensorflow:2.15.0-gpu
                      volumeMounts:
                        - name: shared-env
                          mountPath: /shared-env
                        - name: git-clone-volume
                          mountPath: /git
                      env:
                        - name: PYTHONUNBUFFERED
                          value: "1"
                        - name: NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
