apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: tensorflow-distributed-simple
  namespace: kubeflow-system
spec:
  runtimeRef:
    name: tensorflow-runtime
  trainer:
    image: tensorflow/tensorflow:2.15.0-gpu
    numNodes: 3  # Runtime의 기본값(1) 오버라이드
    command:
      - bash
      - -c
      - |
        # TF_CONFIG 로드
        source /shared-env/tf_config.env
        echo "TF_CONFIG: $TF_CONFIG"

        # Git repo에서 학습 코드 실행
        cd /test
        python3 tensorflow/train.py
    resourcesPerNode:
      limits:
        cpu: "4"
        memory: "16Gi"
        nvidia.com/gpu: "1"
      requests:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: "1"
  # initContainer 설정 + 학습 스크립트 볼륨 마운트
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        volumes:
          - name: astrago-storage-pv-f6-2305-4a58-a987-2132febdab85
            persistentVolumeClaim:
              claimName: astrago-storage-pvc-d0-90d2-4108-be66-7bdd4329ed42
              readOnly: false              
        initContainers:
          - name: git-clone
            env:
              - name: GIT_SYNC_REPO
                value: https://github.com/xiilab/astrago-trainer.git
              - name: GIT_SYNC_BRANCH
                value: main
          # 기존 Runtime의 tf-config-generator에 필드 오버라이드 예시 (머지 대상)
          - name: tf-config-generator
            env:
              - name: TF_PORT
                value: "2333"  # Runtime 기본값을 오버라이드
              - name: NUM_WORKERS
                value: "3"  # TrainJob numNodes 값과 일치시킴
        # NOTE: CRD 제약으로 Pod 메타데이터 오버라이드는 지원되지 않음
        containers:
          - name: node
            volumeMounts:
              - name: git-clone-volume
                mountPath: /test
              - mountPath: /datasets
                name: astrago-storage-pv-f6-2305-4a58-a987-2132febdab85

